### ISSUE TITLE
Display the help to a dxPopup for HTML rendering

### ISSUE THREAD

**Issue by DreamITSoftware** [DevExpress-Examples/asp-net-core-dashboard-custom-properties-sample#2]
I wanted to share the code to allow the DashboardDescription to be displayed in a popup.

Add this to your HTML body 
<div id="helpWidget"></div>

Update onDashboardTitleToolbarUpdated to this

    function onDashboardTitleToolbarUpdated(args) {
        var customProperties = args.dashboard.customProperties;
        var description = customProperties.getValue(dashboardDescriptionProperty.propertyName);
        if (description) {
            args.options.actionItems.push({
                type: "button",
                icon: "iconDescription",
                hint: description,
                click: function () {
                    var popup = null;
                    var popupOptions = {
                        width: 300,
                        height: 250,
                        contentTemplate: description,
                        showTitle: true,
                        title: "Information",
                        visible: false,
                        dragEnabled: false,
                        closeOnOutsideClick: true
                    };                    

                    popup = $("#helpWidget").dxPopup(popupOptions).dxPopup("instance");
                    popup.show();
                }
            });
        }
    };

**Comment by SergeyNakhankov** [comment]
Hello,
Thank you for sharing your code with us. It will be helpful for our community.

**Comment by SergeyNakhankov** [comment]
Hello,

Just a follow-up: To avoid possible XSS vulnerabilities, we don't recommend that you pass strings obtained from the server directly in an HTML template. Use the following approach instead:

`
contentTemplate:  function (element) { element.innerText = description; }
`

**Comment by DreamITSoftware** [comment]
Point well taken Sergey.  Thank you so much
